version: "3.5"

services:
    web:
        build: social/
        restart: on-failure
        ports:
            - "8000:8000"

        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        depends_on:
            - db
    
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/13/main/
        environment:
            - POSTGRES_DB=db_name
            - POSTGRES_USER=db_user
            - POSTGRES_PASSWORD=db_password
volumes:
    postgres_data:
