# Generated by Django 3.1.7 on 2021-03-25 10:08

from django.db import migrations
from profiles import users_generator


def add_males(apps, schema_editor):
    user_instance = apps.get_model("profiles", "UserProfile")
    for i in range(10):
        new_user = users_generator.create_user(users_generator.MALE_USER_NAMES)
        new_obj = user_instance(username=new_user['username'], user_nickname=new_user['user_nickname'], email=new_user['email'],
                                gender=new_user['gender'], subscription=new_user['subscription'],
                                premium_distance=new_user['premium_distance'], latitude=new_user['latitude'],
                                longitude=new_user['longitude'])
        new_obj.save()


def add_females(apps, schema_editor):
    user_instance = apps.get_model("profiles", "UserProfile")
    for i in range(10):
        new_user = users_generator.create_user(users_generator.FEMALE_USER_NAMES)
        new_obj = user_instance(username=new_user['username'], user_nickname=new_user['user_nickname'],
                                gender=new_user['gender'], subscription=new_user['subscription'],
                                premium_distance=new_user['premium_distance'], latitude=new_user['latitude'],
                                longitude=new_user['longitude'])
        new_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_males),
        migrations.RunPython(add_females),
    ]
